- name: Ensure group "zookeeper" exists
  group:
    name: '{{ zookeeper_group }}'
    state: present

- name: Create "zookeeper" service user
  user:
    name: '{{ zookeeper_user }}'
    group: '{{ zookeeper_group }}'
    create_home: false
    shell: /sbin/nologin
    state: present

- name: Download Apache Zookeeper {{ zookeeper_version }}
  get_url:
    url: 'https://archive.apache.org/dist/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz'
    dest: /tmp

- name: Make sure destination dir exists
  file:
    path: '{{ zookeeper_dir }}'
    state: directory
    recurse: yes

- name: Extract the downloaded file
  unarchive:
    src: /tmp/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz
    dest: '{{ zookeeper_dir }}'
    extra_opts: [--strip-components=1]
    remote_src: true

- name: Recursively change ownership of zookeeper installation directory
  file:
    path: '{{ zookeeper_dir }}'
    state: directory
    owner: '{{ zookeeper_user }}'
    group: '{{ zookeeper_group }}'
    recurse: true

- name: Create config directory if it does not exist
  file:
    path: '{{ zookeeper_config_dir }}'
    state: directory
    owner: '{{ zookeeper_user }}'
    group: '{{ zookeeper_group }}'
    mode: '0755'

- name: Create data directory if it does not exist
  file:
    path: '{{ zookeeper_data_dir }}'
    state: directory
    owner: '{{ zookeeper_user }}'
    group: '{{ zookeeper_group }}'
    mode: '0755'

- name: Create configuration zoo.cfg
  template:
    src: zoo.cfg.j2
    dest: '{{ zookeeper_config_dir }}/zoo.cfg'
    owner: '{{ zookeeper_user }}'
    group: '{{ zookeeper_group }}'

- name: Create configuration myid
  template:
    src: myid.j2
    dest: '{{ zookeeper_data_dir }}/myid'
    owner: root
    group: root

- name: Copy systemd service file to server
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
#  notify:
#    - Start zookeeper

- name: Start zookeeper
  shell: 'nohup {{ zookeeper_dir }}/bin/zkServer.sh start {{ zookeeper_config_dir }}/zoo.cfg &'
